/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import modelo.Persona;
import negocio.PersonaServicio;

/**
 *
 * @author Jheyson Gaona
 */
public class SistemaUsuario extends javax.swing.JFrame {

    private PersonaServicio servicio;
    private SimpleDateFormat formato;
    
    // Crear borde de color rojo y negro para visualizar el formulario
    private final Border bordeRojo = BorderFactory.createLineBorder(Color.RED, 2);
    private final Border bordeNegro = BorderFactory.createLineBorder(Color.BLACK, 1);
    
    /**
     * Creates new form PersonUI
     */
    public SistemaUsuario() {
        initComponents();
        servicio = new PersonaServicio();
        formato = new SimpleDateFormat("dd-MM-yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeaderName = new javax.swing.JLabel();
        lblLastnameUser = new javax.swing.JLabel();
        txtLastnameUser = new javax.swing.JTextField();
        lblNameUser = new javax.swing.JLabel();
        txtNameUser = new javax.swing.JTextField();
        lblNumIdUser = new javax.swing.JLabel();
        txtNumIdUser = new javax.swing.JTextField();
        lblEmailUser = new javax.swing.JLabel();
        txtEmailUser = new javax.swing.JTextField();
        lblEmailUser1 = new javax.swing.JLabel();
        btnRegisterUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListUser = new javax.swing.JTable();
        txtDateUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        lblHeaderName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHeaderName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderName.setText("SISTEMA USUARIO");

        lblLastnameUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLastnameUser.setText("Apellido");

        txtLastnameUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtLastnameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameUserActionPerformed(evt);
            }
        });

        lblNameUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNameUser.setText("Nombre");

        txtNameUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameUserActionPerformed(evt);
            }
        });

        lblNumIdUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumIdUser.setText("Número de cédula");

        txtNumIdUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNumIdUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumIdUserActionPerformed(evt);
            }
        });

        lblEmailUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmailUser.setText("Correo electrónico");

        txtEmailUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmailUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailUserActionPerformed(evt);
            }
        });

        lblEmailUser1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmailUser1.setText("Fecha de nacimiento (dd-mm-yyyy)");

        btnRegisterUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegisterUser.setLabel("Registrar");
        btnRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUserActionPerformed(evt);
            }
        });

        tbListUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbListUser);

        txtDateUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumIdUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHeaderName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNameUser, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(lblNameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDateUser, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNumIdUser, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRegisterUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEmailUser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                        .addComponent(lblEmailUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmailUser, javax.swing.GroupLayout.Alignment.LEADING)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeaderName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmailUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumIdUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumIdUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIdUserActionPerformed

    private void txtNameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameUserActionPerformed

    private void txtLastnameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastnameUserActionPerformed

    private void btnRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUserActionPerformed
        // Si el formulario esta lleno proceder a enviarlo a la capa de negocio
        if(ValidarFormulario()){
            // String nombre, String apellido, String numIdentificacion,
            // String correo, Date fechaNacimiento
            String nombre = txtNameUser.getText();
            String apellido = txtLastnameUser.getText();
            String numId = txtNumIdUser.getText();
            String correo = txtEmailUser.getText();
            
            // 26-09-1994
            String fecha = txtDateUser.getText();
            String[] fechaSeparada = fecha.split("-");
            
            int dia = Integer.parseInt(fechaSeparada[0]);
            int mes = Integer.parseInt(fechaSeparada[1]);
            int anio = Integer.parseInt(fechaSeparada[2]);
            LocalDate fechaNacimiento = LocalDate.of(anio, mes, dia);
                    
            Persona nuevaPersona = new Persona(nombre, apellido, numId,
                correo, fechaNacimiento);
            servicio.AgregarNuevaPersona(nuevaPersona);
        }else{
            System.out.println("falta un input de llenar");
            // Mostrar alerta diciendo que llene el formulario
        }
    }//GEN-LAST:event_btnRegisterUserActionPerformed

    private void txtEmailUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailUserActionPerformed

    private void txtDateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateUserActionPerformed

    
    private boolean ValidarFormulario(){
        // Pintar los bordes de cada caja de texto usando operador ternario
        txtNameUser.setBorder(txtNameUser.getText().isEmpty() ? bordeRojo: bordeNegro);
        txtLastnameUser.setBorder(txtLastnameUser.getText().isEmpty() ? bordeRojo: bordeNegro);
        txtNumIdUser.setBorder(txtNumIdUser.getText().isEmpty() ? bordeRojo: bordeNegro);
        txtEmailUser.setBorder(txtEmailUser.getText().isEmpty() ? bordeRojo: bordeNegro);
        
        return !(txtNameUser.getText().isEmpty() || txtLastnameUser.getText().isEmpty()
            || txtNumIdUser.getText().isEmpty() || txtEmailUser.getText().isEmpty());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmailUser;
    private javax.swing.JLabel lblEmailUser1;
    private javax.swing.JLabel lblHeaderName;
    private javax.swing.JLabel lblLastnameUser;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JLabel lblNumIdUser;
    private javax.swing.JTable tbListUser;
    private javax.swing.JTextField txtDateUser;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JTextField txtLastnameUser;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JTextField txtNumIdUser;
    // End of variables declaration//GEN-END:variables
}
